version: "3.8"

services:
  mongodb:
    image: mongo:6.0.1
    restart: always
    ports:
      - 27017:27017
    networks:
      - awesome

  devapi: # back
    image: {{ env.IMAGE_NAME }}
    restart: always
    ports:
      - 3000:3000
    networks:
      - awesome

  # front

networks:
  awesome:
    driver: bridge
